// Code generated by Gojay. DO NOT EDIT.

package test2

import (
	"github.com/francoispqt/gojay"
)

// MarshalJSONObject implements MarshalerJSONObject
func (s *s1) MarshalJSONObject(enc *gojay.Encoder) {
	enc.Int32Key("x", s.x)
	enc.StringKey("y", s.y)
}

// IsNil checks if instance is nil
func (s *s1) IsNil() bool {
	return s == nil
}

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (s *s1) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {

	switch k {
	case "x":
		return dec.Int32(&s.x)

	case "y":
		return dec.String(&s.y)

	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (s *s1) NKeys() int { return 2 }
