name: rust release

on:
  push:
    tags:
      - rust/compiler/v[0-9]*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v3
        # Fetch all history so git describe works
      - run: |
          git fetch --prune --unshallow

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install nightly --profile minimal

      - uses: Swatinem/rust-cache@v2

      - run: cargo +nightly build --release

      - uses: actions/upload-artifact@v3
        with:
          name: radlc-${{ runner.os }}
          path: target/release/radlc

  release:
    name: Create Github Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:

    - name: Fetch macOS build
      uses: actions/download-artifact@v3
      with:
        name: radlc-macOS
        path: radlc-macOS

    - name: Fetch linux build
      uses: actions/download-artifact@v3
      with:
        name: radlc-linux
        path: radlc-linux

    - run: |
        mv radlc-macOS/radlc ./radlc-${GITHUB_REF:24}-osx
        mv radlc-linux/radlc ./radlc-${GITHUB_REF:24}-linux

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        files: |
          radlc-${GITHUB_REF:24}-linux
          radlc-${GITHUB_REF:24}-osx
